# Generated by Django 2.2.4 on 2019-08-02 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_itemseat_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtime',
            name='start_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
