# Generated by Django 2.2.4 on 2019-08-02 02:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190802_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='session',
        ),
        migrations.AddField(
            model_name='session',
            name='showtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='core.Showtime'),
        ),
        migrations.AlterField(
            model_name='itemseat',
            name='seat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='core.Seat'),
        ),
        migrations.AlterField(
            model_name='itemseat',
            name='showtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='core.Showtime'),
        ),
        migrations.AlterField(
            model_name='itemseat',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='session',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to='core.Movie'),
        ),
    ]
