# Generated by Django 2.2.4 on 2019-08-02 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190802_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='type_language',
            field=models.CharField(choices=[('Legendado em português', 'Legendado em português'), ('Dublado em português', 'Dublado em português')], default='Legendado em português', max_length=100),
        ),
    ]
